name: Lab test
on:
  push:
    branches: [ main ]
    paths:
    - 'kubernetes/llama-stack/**'
    - 'kubernetes/notebooks/**'
    - 'demos/rag_agentic/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'kubernetes/llama-stack/**'
    - 'kubernetes/notebooks/**'
    - 'demos/rag_agentic/**'
jobs:
  lab-test:
    runs-on: ubuntu-latest
    environment: ci
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: install oc client
        run: |
          curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/openshift-client-linux.tar.gz
          tar -xvf openshift-client-linux.tar.gz
          sudo mv oc kubectl /usr/local/bin/

      - name: Create project
        run: |
          oc new-project lab-test

      - name: deploy components
        run: |
          oc apply -k kubernetes/kustomize/overlays/demo -n lab-test

      - name: wait for deployment
        run: |
          oc rollout status deployment/llamastack-deployment -n lab-test

      - name: wait for lab pod to be ready
        run: |
          oc wait --for=condition=Ready pod -l app=lab -n lab-test --timeout=300s

      - name: delete project
        if: always()
        run: |
          oc delete project lab-test
